language: haxe

install:
  - yes | haxelib install test.hxml
  - yes | haxelib install hxml/test.cpp.hxml

script:
  - haxe hxml/test.neko.hxml
  - haxe hxml/test.cpp.hxml
  - neko out/neko/test.n
  - ./out/cpp/TestAll-debug
